Converts userAgent to strict format
codex-team/hawk.workers pull request #133
Opened 2020-07-28 17:54 UTC by GeekaN2

Resolves #131

2020-08-20 10:12 UTC, neSpecc requested changes

2020-08-20 10:12 UTC, neSpecc commented on lib/types/event-worker-task.d.ts
> +  addons?: {
addons тоже надо типизировать, их структура известна, хоть и зависит от типа Кэтчера

2020-08-20 10:12 UTC, neSpecc commented on lib/types/event-worker-task.d.ts
> +  os: string;
не описаны поля

2020-08-20 10:12 UTC, neSpecc commented on workers/javascript/src/index.ts
> +      event.payload.addons.userAgent = this.beautifyUserAgent(event.payload.addons.userAgent.toString());
оригинальную строку userAgent не надо перезаписывать, она может пригодиться. Надо либо сохранить распаршенные данные в отдельное поле, либо внутрь UserAgent добавить поле original

2020-08-20 10:12 UTC, neSpecc commented on workers/javascript/src/index.ts
> +   * @returns {string}
```suggestion
```

2020-08-20 10:12 UTC, neSpecc commented on workers/javascript/src/index.ts
> +    const agent = useragent.parse(userAgent);
тут не нужен try catch?

2020-08-20 10:12 UTC, neSpecc commented on workers/javascript/tests/index.test.ts
> +      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0'
а где тест на это?

2021-04-02 08:09 UTC, talyguryn approved these changes

2021-04-02 09:24 UTC, neSpecc commented on workers/javascript/src/index.ts
> +    event.payload.addons.beautifiedUserAgent = this.beautifyUserAgent(event.payload.addons.userAgent.toString());
userAgent может не быть, лучше добавить проверку

2021-04-02 09:24 UTC, neSpecc commented on workers/javascript/src/index.ts
> +      this.logger.error('Cannot parse user-agent ' + userAgent);
так он парсится вне try

2021-04-02 09:24 UTC, neSpecc commented on workers/javascript/src/index.ts
> +    const agent = useragent.parse(userAgent);
нет ответа

2021-04-02 09:24 UTC, neSpecc commented on workers/javascript/tests/index.test.ts
> +  userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0',
а где тест парсинга?

2021-04-02 09:24 UTC, neSpecc commented on workers/slack/src/templates/utils.ts
> +  const jsAddons = addons as JavaScriptAddons;
хардкод

2021-04-02 14:28 UTC, GeekaN2 commented on workers/slack/src/templates/utils.ts
> +  const jsAddons = addons as JavaScriptAddons;
А если так?
![изображение](https://user-images.githubusercontent.com/40016207/113424298-9c557f80-93d8-11eb-8e07-e5cc296acab2.png)

2021-04-02 14:29 UTC, neSpecc commented on workers/slack/src/templates/utils.ts
> +  const jsAddons = addons as JavaScriptAddons;
в ветке виталика уже пофикшено

2021-04-17 09:18 UTC, nikmel2803 approved these changes

2021-04-18 13:04 UTC, neSpecc approved these changes

2021-04-18 13:13 UTC, merged