Encode unsafe fields
codex-team/hawk.workers pull request #145
Opened 2020-09-09 04:47 UTC by nikmel2803

MongoDB запрещает использовать некоторые символы в ключах объектах (например, точку) из-за чего возникает ошибка при сохранении некоторых ивентов (https://beta.hawk.so/project/5ee7a80de6ce2b651831f26e/event/5f496e7139ec973ff9edf0a9/overview)

Чтобы этого избежать, мы превращаем в строку поля, структура которых точно заранее неизвестна (context, addons) и сохраняем в БД в виде строки

2020-09-09 06:56 UTC, neSpecc commented on lib/types/event-worker-task.d.ts
> +  addons?: {[key: string]: string|object} | string;
на вход же всегда object приходит от кэтчеров.

2020-09-09 06:56 UTC, neSpecc commented on workers/grouper/src/index.ts
> +      if (typeof event.payload.context !== 'string') {
названия полей надо куда-то вынести и не дублировать код ರ_ರ

2020-09-21 09:23 UTC, neSpecc commented on workers/slack/src/templates/utils.ts
> +  decodeUnsafeFields(event);
это можно в абстрактного воркера `Sender` вынести, туда, где ивент достается из базы

2020-09-21 21:15 UTC, neSpecc commented on workers/grouper/src/index.ts
> +      decodeUnsafeFields(existedEvent);
опиши в комментах, зачем тут декод

2020-09-22 17:08 UTC, talyguryn requested changes

2020-09-22 17:08 UTC, talyguryn commented on workers/grouper/tests/index.test.ts
> +        data: { 'test-test': false },
протестировать данные с точкой в ключе, чтобы убедиться, что реквест решает проблему

2020-09-22 17:19 UTC, neSpecc approved these changes

2020-09-22 18:05 UTC, talyguryn approved these changes

2020-09-22 18:05 UTC, merged