Fix error when running some workers in docker container
codex-team/hawk.workers pull request #153
Opened 2020-09-23 13:34 UTC by nikmel2803

closes #142 
- пофиксил ошибку в issue
- убрал лишние tsconfig

2020-09-23 15:00 UTC, kabachook approved these changes

2020-09-23 15:01 UTC, kabachook requested changes

2020-09-23 15:01 UTC, kabachook commented on workers/email/scripts/emailOverview.ts
> +import type { EventsTemplateVariables, TemplateEventData } from 'hawk-worker-sender/types/template-variables';
tag me when is ready

2020-09-24 18:27 UTC, kabachook approved these changes

2020-09-24 21:54 UTC, neSpecc approved these changes

2020-09-24 21:54 UTC, merged