Implement simple Golang worker
codex-team/hawk.workers pull request #169
Opened 2020-11-05 12:56 UTC by n0str

2020-11-09 07:06 UTC, neSpecc requested changes

2020-11-09 07:06 UTC, neSpecc commented on workers/go/src/index.ts
> +    await this.db.connect();
если в этом воркере не используется база, то лучше и не делать коннект

2020-11-11 15:51 UTC, neSpecc approved these changes

2020-11-16 07:12 UTC, talyguryn approved these changes

2020-11-16 07:51 UTC, merged