Limiter worker implementation
codex-team/hawk.workers pull request #171
Opened 2020-11-17 22:01 UTC by nikmel2803

2020-11-18 06:20 UTC, neSpecc commented on workers/limiter/src/index.ts
> +            console.log('error');
тут бы еще отправить ошибку в хоука

2020-11-18 06:20 UTC, neSpecc commented on workers/limiter/src/index.ts
> +      this.projectsCollection.find({}).toArray(),
это тоже вынести бы в метод getAllProjects, чтобы по красоте было

2020-11-18 06:20 UTC, neSpecc commented on workers/limiter/src/index.ts
> +        projectIds = [
давай лучше `projectIds.push(...)`, читаться будет лучше

2020-11-18 06:20 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    if (!workspace.lastChargeDate) {
не понятная строка. А если списание было год назад, а теперь я на бесплатном тарифе?

2020-11-18 06:20 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    if (!workspace.lastChargeDate) {
нужен коммент, или вынести в метод

2020-11-18 06:20 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    this.logger.info('Limiter worker finished task');
и давай добавим отчет в телеграм

2020-11-23 23:11 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +            console.log('error');
done

2020-11-23 23:13 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +      this.projectsCollection.find({}).toArray(),
done

2020-11-23 23:15 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +        projectIds = [
done

2020-11-23 23:18 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +    if (!workspace.lastChargeDate) {
Я решил, что если нету этой даты, то это забота Paymaster воркера. Значит при следующем его запуске он поставит эту дату и тогда лимитер спокойно обработает этот воркспейс. Ничего страшного. Коммент добавлю

2020-11-24 01:43 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +    this.logger.info('Limiter worker finished task');
done

2020-11-24 02:04 UTC, neSpecc reviewed
Worker's Readme is missed

2020-11-24 02:10 UTC, neSpecc requested changes

2020-11-24 02:10 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    }
а удалять из редиса кто будет?

2020-11-24 02:10 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    workspacesMap: Record<string, WorkspaceWithTariffPlan>,
зачем передается непонятное `workspacesMap`, если используется всегда `workspacesMap[project.workspaceId.toString()`? лучше это и передавать. 

Или я не понимаю код? у всех `projects` же одинаковый worksaceId?

2020-11-24 02:10 UTC, neSpecc commented on workers/limiter/src/index.ts
> +  private async getTotalEventsCountByWorkspace(
судя по тому, что на вход передается не воркспейс, а проекты, метод должен называться не byWorkspace, а byWorkspaceProjects

2020-11-24 02:11 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +    }
он полностью перезаписывает значение по ключу

2020-11-24 02:13 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    const projectIdsToBan = await this.getProjectsIdsToBan(reportData);
зачем во все методы прикидывается `reportData`? не красиво как-то. Они могут возвращать просто данные наверх? и в handle собрать уже reportData

2020-11-24 02:14 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    }
тогда напиши это в описании метода.

2020-11-24 02:15 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    const [repetitionsCount, originalEventCount] = await Promise.all([repetitionsCollection.find(query).count(), eventsCollection.find(query).count()]);
тут не нужны try-catch?

2020-11-24 02:15 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +    const projectIdsToBan = await this.getProjectsIdsToBan(reportData);
тогда будут некрасивые возвращаемые значения(
либо объект с дополнительной информацией возвращать надо будет, либо массив

2020-11-24 02:16 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    }
а если `projectIdsToBan.length === 0` , то старые проекты так и останутся забаненными?

2020-11-24 02:19 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    const projectIdsToBan = await this.getProjectsIdsToBan(reportData);
нормально будет, порефактори только немного 

```suggestion
    const projectToBan = await this.getProjectsToBan();
```

и тд

2020-11-24 02:21 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +    const projectIdsToBan = await this.getProjectsIdsToBan(reportData);
ну а инфу о забаненных воркспейсах о воркспейсах без даты последнего списания как прокидывать?
возвращать вместе с проектами из getProjectsToBan? и их других функций тоже?

2020-11-24 02:23 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    const projectIdsToBan = await this.getProjectsIdsToBan(reportData);
нет, надо декомпозировать `getProjectsIdsToBan` на методы. Сейчас он много всего делает, даже апдейты какие-то — это не соответствует названию и отсюда у тебя проблемы с прокидыванием

2020-11-24 02:26 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    const projectIdsToBan = await this.getProjectsIdsToBan(reportData);
и наверное можно переделать на getWorkspacesToBan , которая вернет воркспейсы и проекты

2020-11-24 17:33 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    const [projects, workspacesMap] = await Promise.all([
почему не назвать `workspacesWithTariffPlans` или `workspacesWithPlans`?

2020-11-24 17:33 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    await asyncForEach(Object.entries(totalEventsCountByWorkspace), async ([workspaceId, eventsCount]) => {
это не вынести в метод?

2020-11-24 17:34 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +    const [projects, workspacesMap] = await Promise.all([
звучит как массив

2020-11-24 21:17 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    const [projects, workspacesMap] = await Promise.all([
а `workspacesMap` звучит как не понятно что. Код от этого становится менее понятным

2020-11-24 21:18 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +    const [projects, workspacesMap] = await Promise.all([
эээ Map — сущность ключ-значение, чего непонятного

2020-11-24 21:34 UTC, neSpecc commented on workers/limiter/README.md
> +If so, the limiter puts information in Redis about the workspace's projects for which it is necessary to stop accepting events.
```suggestion
If so, the Limiter puts information to Redis about the workspace's projects for which it is necessary to stop accepting events.
```

2020-11-24 21:34 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    const [projects, workspacesMap] = await Promise.all([
не понятно, что за данные там лежат. Что мапится? Как это следует из названия?

2020-11-24 21:34 UTC, neSpecc commented on workers/limiter/src/index.ts
> +    await this.calculateWorkspacesTotalEventsCount(projects, workspacesMap);
давай сделаем код лучше: функция должна вернуть значение. Следующая часть кода работает с этим значением. А сейчас там что-то прокидывается внутрь, изменяется, а потом используется в другом месте

2020-11-24 21:39 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +    const [projects, workspacesMap] = await Promise.all([
а из workspacesWithPlans как-то можно понять что это не массив, а ключ-значение?
в workspacesMap может возникнуть вопрос разве о том, что является ключом, но я решил не усложнять название

2020-11-24 21:39 UTC, nikmel2803 commented on workers/limiter/src/index.ts
> +    await this.calculateWorkspacesTotalEventsCount(projects, workspacesMap);
как-то иммутабельность в воркерах нас раньше не волновала
ну да ок, сделаю

2020-12-03 04:31 UTC, neSpecc commented on workers/limiter/src/index.ts
> +   *
```suggestion
   * Checks which workspaces reached the limit and return them along with their projects ids.
   * Also, updates workspace current event count in db.
```

2020-12-03 04:33 UTC, neSpecc approved these changes

2020-12-03 08:46 UTC, ilyamore88 approved these changes

2020-12-03 09:32 UTC, n0str approved these changes

2020-12-03 09:32 UTC, merged