Fix an issue where lastChargeDate wasn't updated if the plan was free
codex-team/hawk.workers pull request #177
Opened 2020-12-02 17:41 UTC by GeekaN2

2020-12-03 04:23 UTC, neSpecc commented on workers/paymaster/src/index.ts
> +   * @param date - date for syncing updated fields
не понятно описана проблема

2020-12-03 13:09 UTC, GeekaN2 commented on workers/paymaster/src/index.ts
> +   * @param date - date for syncing updated fields
Я обновление lastChargeDate вынес в отдельную функцию, поэтому, чтобы эта дата совпадала с датой в бизнес операции я её передаю. Посмотри предыдущие коммиты, там другое решение.

2020-12-03 15:15 UTC, neSpecc commented on workers/paymaster/src/index.ts
> +   * @param date - date for syncing updated fields
я понимаю, но в комментарии к параметру это не объясняется.

2020-12-04 10:36 UTC, nikmel2803 requested changes
не вижу никаких изменений в тестах
нужно либо пофиксить существующий тест, либо добавить новый, который проверяет, что такой проблемы больше нет

2020-12-04 19:54 UTC, ilyamore88 approved these changes

2020-12-14 08:56 UTC, neSpecc approved these changes

2020-12-14 17:04 UTC, nikmel2803 approved these changes

2020-12-14 17:34 UTC, merged