[Feature] Limiter tests
codex-team/hawk.workers pull request #178
Opened 2020-12-03 19:48 UTC by ilyamore88

Adds tests for limiter worker.

2020-12-04 15:31 UTC, neSpecc requested changes

2020-12-04 15:31 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    expect(workspace.billingPeriodEventsCount).toEqual(18);
откуда это число?

2020-12-04 15:31 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +  test('Should correctly count billing period events', async () => {
что значит "корректно"?

2020-12-04 15:31 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +  test('Should put banned projects to redis', async (done) => {
не понятно описан кейс

2020-12-04 15:31 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +
Не хватает тестов
- should unban previously banned projects
- should not ban project if it does not reach the limit
- should not ban project on the free tariff plan
- should send a report with collected data

2020-12-04 15:31 UTC, neSpecc commented on workers/limiter/tests/repetitions.mock.ts
> +export const mockedRepetitions = [
нет описания

2020-12-04 15:31 UTC, neSpecc commented on workers/limiter/tests/events.mock.ts
> +export const mockedEvents = [
опиши, что это за ивенты, для чего, что они имитируют?

2020-12-04 15:46 UTC, ilyamore88 commented on workers/limiter/tests/index.test.ts
> +
А какой кейс тестируется в тесте `should not ban project on the free tariff plan`? Это такой же тарифный план, как и платный, только с другим лимитом по эвентам.

2020-12-04 18:06 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +
ok

2020-12-09 12:53 UTC, neSpecc commented on workers/limiter/tests/workspaces.mock.ts
> +    tariffPlanId: new ObjectId('5e4ff528628a6c714515f4dc'),
id плана тоже лучше расхардкодить и взять из `plans.mock.ts`. Можно через find по `eventsLimit`. Чтобы мог был понятнее

2020-12-09 12:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +      expect(result).toContain(mockedProjects[2]._id.toString());
mockedProjects[2] надо вынести в переменную

2020-12-09 12:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    /**
а где в этом тесте `Arrange`, то есть подготовка состояния? не вижу тут забаненного пронекта

2020-12-09 12:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +      expect(result).not.toContain(mockedProjects[1]._id.toString());
mockedProjects[1] надо вынести в переменную с понятным названием

2020-12-09 12:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +      _id: mockedWorkspaces[0]._id,
`mockedWorkspaces[0]._id` - не понятный код с magic number. Лучше вынести в переменную mockedWorkspaces[0],

2020-12-09 12:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +      _id: mockedWorkspaces[0]._id,
а нельзя обращаться к воркспейсам не по индексу, а через find например?

2020-12-09 12:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +     * Check count of events
не понятно, как комментарий относится к последующему коду

2020-12-09 12:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    /**
пропущен `Arrange`

2020-12-09 12:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    /**
пропущен Arrange, сразу идет Act

2020-12-14 08:53 UTC, neSpecc requested changes

2020-12-14 08:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    connection = await MongoClient.connect(process.env.MONGO_ACCOUNTS_DATABASE_URI, {
настояющая база испольузуется в тестах?

2020-12-14 08:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    const workspace = mockedWorkspaces[0];
magic number

2020-12-14 08:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +  test('Should count billing period events of workspace', async () => {
```suggestion
  test('Should count workspace events for a billing period and save it to the db', async () => {
```

2020-12-14 08:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    const workspace = mockedWorkspaces[3];
magic number

2020-12-14 08:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    const workspace = mockedWorkspaces[3];
плохая идея держать все в куче `mockedWorkspaces` — не читается код вообще

2020-12-14 08:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    const workspace = mockedWorkspaces[2];
опять какие-то магические числа. Все эти строки не понятные. Должно быть ясно видно где `previously banned projects` и где `limit allows`

2020-12-14 08:53 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    await repetitionsCollection.insertMany(mockedRepetitions);
все это повторяется из раза в раз — можно вынести в функцию

2020-12-14 18:04 UTC, ilyamore88 commented on workers/limiter/tests/index.test.ts
> +    connection = await MongoClient.connect(process.env.MONGO_ACCOUNTS_DATABASE_URI, {
Используется монга, которая для тестов запускается в оперативке с помощью `mongodb-memory-server`.

2020-12-16 09:25 UTC, nikmel2803 approved these changes

2020-12-16 10:13 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    await fillDatabaseWithMockedData(workspace, project);
Arrange должен иллюстрировать спек, описанный в тесте.
Например так:

```js
const workspace = createWorkspaceMock({
   plan: mockedPlans.eventsLimit10,
   billingPeriodEventsCount: 0,
   lastChargeDate: LAST_CHARGE_DATE,
});

await fillDatabaseWithMockedData({ workspace, project, eventsToMock: 11 });
```

2020-12-16 10:13 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    redisClient.smembers('DisabledProjectsSet', (err, result) => {
оставь тут коммент для потомков плз

2020-12-16 10:13 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    await workspaceCollection.findOneAndUpdate({ _id: workspace._id }, {
и тут

2020-12-16 10:13 UTC, neSpecc commented on workers/limiter/tests/index.test.ts
> +    await fillDatabaseWithMockedData(workspace, project);
тут тоже явно надо укзаать, что создастся меньше 10000

2020-12-24 18:25 UTC, neSpecc approved these changes

2020-12-24 18:29 UTC, merged