Payment failed
codex-team/hawk.workers pull request #190
Opened 2021-02-27 15:35 UTC by GeekaN2

2021-03-11 16:20 UTC, ilyamore88 approved these changes
Скорее бы в мастер...
👉👈

2021-03-12 11:04 UTC, neSpecc requested changes

2021-03-12 11:04 UTC, neSpecc commented on workers/email/src/templates/components/workspace.twig
> +                                     alt="{{ workspace.name }}"
проверь, работает ли тут экранирование по умолчанию или надо добавлять вручную?

2021-03-12 11:04 UTC, neSpecc commented on workers/email/src/templates/emails/payment-failed/html.twig
> +        Rejection reason: {{ reason }}
не по макету

2021-03-15 15:09 UTC, nikmel2803 approved these changes

2021-03-16 17:49 UTC, neSpecc requested changes

2021-03-16 17:49 UTC, neSpecc commented on workers/email/src/templates/components/workspace.twig
> +                                     alt="{{ workspace.name | escape }}"
escapeAttr ?

2021-03-16 18:42 UTC, neSpecc approved these changes

2021-03-16 18:43 UTC, merged