[Feature] Block workspace message in sender worker
codex-team/hawk.workers pull request #191
Opened 2021-02-27 16:19 UTC by ilyamore88

Adds types and logic for block workspace message to sender worker. For #185.

2021-02-27 18:23 UTC, nikmel2803 commented on workers/sender/src/index.ts
> +    const confirmedMembers = workspaceTeam.filter(member => (member as ConfirmedMemberDBScheme).userId) as ConfirmedMemberDBScheme[];
можно изначально в БД составить запрос, чтобы получить только confirmed members

2021-02-27 18:43 UTC, GeekaN2 commented on workers/sender/src/index.ts
> +      this.provider.send(channel.endpoint, {
Надо добавить проверку `if (channel.isEnabled)`

2021-02-27 21:15 UTC, nikmel2803 approved these changes
типы бы вынести

2021-02-27 21:26 UTC, GeekaN2 approved these changes

2021-02-28 03:40 UTC, neSpecc requested changes

2021-02-28 03:40 UTC, neSpecc commented on workers/sender/src/index.ts
> +    const users = await this.getUsers(confirmedMemberIds);
наверное надо отправлять только админам

2021-03-01 14:31 UTC, neSpecc approved these changes

2021-03-01 14:32 UTC, merged