Move functions to eventworker
codex-team/hawk.workers pull request #199
Opened 2021-03-29 18:04 UTC by talyguryn

2021-04-01 07:30 UTC, neSpecc requested changes

2021-04-01 07:30 UTC, neSpecc commented on lib/event-worker.ts
> + * Used to extract Project Id from Integration Token
```suggestion
```

2021-04-01 07:30 UTC, neSpecc commented on lib/event-worker.ts
> + * and to provide some common methods.
```suggestion
 * Used for the common language-workers that require no specific logic (source maps consuming etc). Other workers can override `handle()` method 
```

2021-04-01 07:30 UTC, neSpecc commented on workers/php/tests/index.test.ts
> +  test('should start correctly', async () => {
unuseful test

2021-04-01 07:30 UTC, neSpecc commented on workers/php/tests/index.test.ts
> +  test('should not handle bad event data', async () => {
Seems like this test is related to the EventWorker, not PhpWorker

2021-04-01 07:30 UTC, neSpecc commented on workers/php/tests/index.test.ts
> +  test('should handle good event data', async () => {
Seems like this test is related to the EventWorker, not PhpWorker

2021-04-01 07:30 UTC, neSpecc commented on workers/php/tests/index.test.ts
> +  test('should finish correctly', async () => {
unuseful test

2021-04-01 07:30 UTC, neSpecc commented on workers/php/tests/index.test.ts
> +jest.mock('amqplib');
are you sure this is necessary?

2021-04-01 07:30 UTC, neSpecc commented on workers/php/tests/rabbit.mock.ts
> +import amqp from 'amqplib';
i think this mock can be deleted at all

2021-04-01 07:30 UTC, neSpecc commented on workers/php/types/php-event-worker-task.d.ts
> +interface PhpEventPayload extends DecodedEventData {}
pull the new version of the `hawk.types` package , please. There should be a generic with Addons. Something like that:

```ts
interface PhpEventPayload extends DecodedEventData<PhpAddons> {}
```

2021-04-01 08:44 UTC, neSpecc commented on workers/php/types/php-event-worker-task.d.ts
> +interface PhpEventPayload extends DecodedEventData<EventAddons> {}
There should be `PhpAddons`. Described [there](https://github.com/codex-team/hawk.types/blob/master/src/base/event/addons/php.ts)

2021-04-02 09:25 UTC, neSpecc approved these changes

2021-04-03 12:04 UTC, nikmel2803 commented on workers/python/src/index.ts
> +    return super.handle(event);
и тут

2021-04-03 13:31 UTC, talyguryn commented on workers/nodejs/src/index.ts
> +    return super.handle(event);
оставил эти методы только для указания особого типа переменной

![image](https://user-images.githubusercontent.com/15259299/113479847-f5391c80-9499-11eb-8ff7-165c9b0b45ad.png)

2021-04-03 17:06 UTC, nikmel2803 approved these changes

2021-04-05 09:34 UTC, merged