Add release for suspected commits
codex-team/hawk.workers pull request #200
Opened 2021-04-05 17:02 UTC by GeekaN2

Handle the add-release task and save the release to the database

2021-05-17 07:02 UTC, nikmel2803 commented on workers/release/src/index.ts
> +            commits: commits,
коммиты будут сохраняться строкой?

2021-05-17 07:03 UTC, GeekaN2 commented on workers/release/src/index.ts
> +            commits: commits,
там JSON.parse сверху, это массив

2021-05-17 07:05 UTC, nikmel2803 commented on workers/release/src/index.ts
> +            commits: commits,
<img width="343" alt="image" src="https://user-images.githubusercontent.com/32655339/118445663-66096080-b6f7-11eb-9641-467ebd8ca153.png">

2021-05-17 07:11 UTC, nikmel2803 commented on workers/release/src/index.ts
> +        .collection(this.dbCollectionName)
чтобы TS знал что храниться в коллекции надо указать collection<Type>(name)
тогда не будет ошибок из-за отсутствия типизации

2021-06-01 13:08 UTC, nikmel2803 requested changes

2021-06-01 13:08 UTC, nikmel2803 commented on workers/release/tests/index.test.ts
> +    const extendedInfo: SourceMapDataExtended[] = workerInstance['extendReleaseInfo']([ {
лучше проверять всё на публичных методах. И проверять работу внутренних компонентах по итоговому результату. В данном случае, лучше закинуть файл с нужным названием, вызвать handle и посмотреть, успешно ли он его обработал

2021-06-01 13:08 UTC, nikmel2803 commented on workers/release/src/index.ts
> +        .collection(this.dbCollectionName)
у тебя везде без этого толком типизация не работает

2021-06-01 13:08 UTC, nikmel2803 commented on workers/release/src/index.ts
> +        .collection(this.dbCollectionName)
```
this.db.getConnection()
         .collection(this.dbCollectionName)
```

вынести это в отдельное св-во, раз ты часто к этому обращаешься

2021-06-01 13:08 UTC, nikmel2803 commented on workers/release/src/index.ts
> +  private async saveSourceMapJS(releaseData: SourceMapsRecord): Promise<ObjectId | null> {
1) логика кажется слишком замудрёной. Приходится достаточно много времени тратить на то, чтобы во всём разобраться (я так этого и не сделал). Этот код требует рефакторинга. Может можно как-то оптимизировать логику, разнести на более понятные методы или типо того?
2) Смущает нейминг saveSourceMap и saveSourceMapJS нейминг похожий, но ф-ии разные. 
3)

2021-06-03 18:21 UTC, GeekaN2 commented on workers/release/README.md
> +2. REWRITE THIS DOC PLEASE
Outdated

2021-06-04 17:19 UTC, GeekaN2 commented on workers/release/src/index.ts
> +      this.logger.error(`Couldn't save the release due to: ${err}`);
У меня нет вариантов куда в другое место валидацию коммитов вынести, поэтому она здесь

2021-06-06 10:35 UTC, neSpecc approved these changes

2021-06-06 10:35 UTC, neSpecc commented on workers/release/README.md
> +# Source map parsing
```suggestion
# Release worker
```

2021-06-06 10:35 UTC, neSpecc commented on workers/release/README.md
> +## Parsing scheme
```suggestion
## Source maps delivery scheme
```

2021-06-07 09:39 UTC, nikmel2803 commented on workers/release/src/index.ts
> + * Java Script releases worker
только JS? он не абстрактный?

2021-06-07 09:39 UTC, nikmel2803 commented on workers/release/src/index.ts
> +   * Worker type (will pull tasks from Registry fqueue with the same name)
```suggestion
   * Worker type (will pull tasks from Registry queue with the same name)
```

2021-06-07 09:39 UTC, nikmel2803 commented on workers/release/README.md
> +3. After Webpack finished his job, our **Webpack Plugin** gets a source maps for new bundles and sends them to us.
ссылку лучше вставить, мне кажется

2021-06-07 09:39 UTC, nikmel2803 commented on workers/release/README.md
> +3. After Webpack finished his job, our **Webpack Plugin** gets a source maps for new bundles and sends them to us.
на плагин

2021-06-07 12:48 UTC, nikmel2803 approved these changes

2021-06-07 12:54 UTC, merged